"""empty message

Revision ID: c051900511cb
Revises: 
Create Date: 2020-03-05 11:10:21.331368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c051900511cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
